### ISSUE TITLE
Template possible?

### ISSUE THREAD

**Issue by EoinKenny** [Lornatang/PyTorch-NCSN#2]
Hi thanks for making this code available.

I'm interested in using the GAN in a larger project with a generative component. The code structure here is fairly complex and I'm wondering if you could please supply a simple template which (1) loads the model class, (2) the pre-trained weights, and (3) generates some samples. Preferably in a jupyter notebook format.

I realise this isn't a real "issue", but it would really help most people get to "playing" with the model faster. Thank you, and happy new year. :-)

**Comment by Lornatang** [comment]
Oh

**Comment by EoinKenny** [comment]
Sorry what?

**Comment by Lornatang** [comment]
I did n’t want to maintain it anymore because I was working on the EfficientNet network recently，lol @EoinKenny

**Comment by EoinKenny** [comment]
Cool! Thanks for the heads up

**Comment by Lornatang** [comment]
Are you interested in GAN? @EoinKenny

**Comment by EoinKenny** [comment]
Yes I would like to use it and cite it in a research paper

**Comment by Lornatang** [comment]
yes.  I very like it.
