### ISSUE TITLE
BaselineRunner is not defined

### ISSUE THREAD

**Issue by vishal3477** [Lornatang/PyTorch-NCSN#3]
Hi, I am getting an error BaselineRunner is not defined. Can you please help me with this? Thank you.

**Comment by Lornatang** [comment]
@vishal3477  Please give detailed error information.

**Comment by vishal3477** [comment]
Traceback (most recent call last):
  File "main.py", line 165, in <module>
    sys.exit(main())
  File "main.py", line 153, in main
    runner = eval(args.runner)(args, config)
  File "string", line 1, in module
NameError: name 'AnnealRunner' is not defined
